<?php
/**
 * GETONLINE STUDIO - CITY PILLAR EDITOR (Standalone)
 * Dedicated AI Engine for 700+ word local SEO content.
 */

// 1. Boot up WordPress silently
define('WP_USE_THEMES', false);
require_once(__DIR__ . '/wp/wp-load.php'); // Adjust path if needed

// 2. Security Check
if (!is_user_logged_in() || !current_user_can('manage_options')) {
    wp_redirect('/wp-login.php');
    exit;
}

$message = '';

// Save Logic
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action']) && $_POST['action'] === 'save_city_pillar') {
    $city_id = intval($_POST['city_id']);
    // We use wp_kses_post to safely allow HTML generated by the AI
    $city_long_content = wp_kses_post($_POST['city_long_content']);
    
    if($city_id > 0) {
        update_post_meta($city_id, 'city_long_content', $city_long_content);
        $message = "Long-form City Pillar saved successfully!";
    }
}

// ── AI FAQ GENERATION HANDLER ──
// Called via AJAX (fetch POST) from the browser. Returns JSON.
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action']) && $_POST['action'] === 'generate_city_faqs') {
    header('Content-Type: application/json');

    $city_id = intval($_POST['city_id'] ?? 0);
    if (!$city_id) { echo json_encode(['ok' => false, 'msg' => 'No city ID.']); exit; }

    $city_obj = get_post($city_id);
    if (!$city_obj) { echo json_encode(['ok' => false, 'msg' => 'City not found.']); exit; }

    $city_name_gen = $city_obj->post_title;
    $api_key = 'AIzaSyC1DPDJzt5psEkIDgqK3XztuVLgXnDwwZM';

    $prompt = "You are a local SEO expert for GetOnline Studio, a Nigerian web design and digital agency.
Generate exactly 6 FAQs for the city hub page targeting businesses in {$city_name_gen}, Nigeria.

Requirements:
- FAQ 1: About web design pricing in {$city_name_gen} (mention Naira ranges naturally, e.g. ₦120,000 to ₦600,000+)
- FAQ 2: About how long it takes to build a website
- FAQ 3: About what types of businesses in {$city_name_gen} need websites most urgently
- FAQ 4: Clarify the difference between web designer, web developer, and web design agency
- FAQ 5: About local SEO and ranking on Google Maps and search results in {$city_name_gen}
- FAQ 6: A question specific to the business culture or economy of {$city_name_gen}

Rules:
- Each answer must be 2-3 sentences.
- Mention GetOnline Studio naturally in exactly 2 of the 6 answers.
- Do NOT use forbidden phrases: 'In today's digital age', 'Elevate', 'Unlock potential', 'Seamless', 'Bustling', 'Vibrant'.
- Write at a clear, accessible level. Short sentences.

Return ONLY a valid JSON array — no markdown, no preamble, no backticks:
[{\"q\": \"...\", \"a\": \"...\"}]";

    $response = wp_remote_post(
        'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent?key=' . urlencode($api_key),
        [
            'timeout' => 45,
            'headers' => ['content-type' => 'application/json'],
            'body'    => json_encode([
                'contents'        => [['role' => 'user', 'parts' => [['text' => $prompt]]]],
                'generationConfig' => ['maxOutputTokens' => 1500, 'temperature' => 0.7]
            ])
        ]
    );

    if (is_wp_error($response)) {
        echo json_encode(['ok' => false, 'msg' => 'API error: ' . $response->get_error_message()]);
        exit;
    }

    $body      = json_decode(wp_remote_retrieve_body($response), true);
    $raw_text  = $body['candidates'][0]['content']['parts'][0]['text'] ?? '';
    // Strip any accidental markdown fences
    $raw_text  = preg_replace('/```json|```/', '', $raw_text);
    $faqs      = json_decode(trim($raw_text), true);

    if (!is_array($faqs) || count($faqs) < 4) {
        echo json_encode(['ok' => false, 'msg' => 'AI returned invalid JSON. Raw: ' . substr($raw_text, 0, 200)]);
        exit;
    }

    update_post_meta($city_id, '_pseo_city_faqs',     $faqs);
    update_post_meta($city_id, '_pseo_city_faq_date', current_time('mysql'));

    echo json_encode(['ok' => true, 'msg' => count($faqs) . ' FAQs generated and saved for ' . $city_name_gen . '.', 'count' => count($faqs)]);
    exit;
}

// Fetch Cities
$locations = get_posts([
    'post_type' => 'pseo_location',
    'numberposts' => -1,
    'post_status' => ['publish', 'draft'],
    'orderby' => 'title',
    'order' => 'ASC'
]);

$edit_city_id = isset($_GET['edit_city']) ? intval($_GET['edit_city']) : ($locations[0]->ID ?? 0);

$selected_city_name = '';
$selected_city_long_content = '';
foreach($locations as $loc) {
    if($loc->ID == $edit_city_id) {
        $selected_city_name = $loc->post_title;
        $selected_city_long_content = get_post_meta($loc->ID, 'city_long_content', true);
        break;
    }
}
?>
<!DOCTYPE html>
<html lang="en" class="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>City Pillar Editor | GetOnline Studio</title>
    <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;600;700&family=Syne:wght@700&display=swap" rel="stylesheet">
    <script src="https://unpkg.com/lucide@latest"></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {
            darkMode: 'class',
            theme: {
                extend: {
                    colors: {
                        'matte-black': '#0a0a0a', 'panel-dark': '#121212', 'card-dark': '#1a1a1a',
                        'lavender': '#e9d5ff', 'sharp-purple': '#7e22ce', 'success-green': '#4ade80',
                    },
                    fontFamily: { 'syne': ['Syne', 'sans-serif'], 'manrope': ['Manrope', 'sans-serif'] }
                }
            }
        }
    </script>
    <style>
        body { background-color: #0a0a0a; color: #e9d5ff; font-family: 'Manrope', sans-serif; }
        textarea { transition: border-color 0.2s; }
    </style>
</head>
<body class="p-6 md:p-12">

    <?php if($message): ?>
    <div id="toast" class="fixed top-6 right-6 z-[100] bg-success-green/20 border border-success-green/40 text-success-green px-6 py-4 rounded-lg flex items-center gap-3">
        <i data-lucide="check-circle" class="w-5 h-5"></i>
        <span class="font-bold text-sm"><?= $message ?></span>
    </div>
    <script>setTimeout(() => document.getElementById('toast').style.display = 'none', 3000);</script>
    <?php endif; ?>

    <!-- FAQ Generation Toast (hidden by default) -->
    <div id="faq-toast" class="fixed top-6 right-6 z-[100] hidden px-6 py-4 rounded-lg flex items-center gap-3 border text-sm font-bold"></div>

    <div class="max-w-5xl mx-auto">
        <div class="flex flex-col md:flex-row justify-between items-start md:items-end mb-8 gap-4">
            <div>
                <h1 class="font-syne text-3xl font-bold text-white mb-2">City Pillar Editor</h1>
                <p class="text-sm text-lavender/60">Generate 700+ word, SEO-optimized definitive guides (Brian Dean Style).</p>
            </div>
            <a href="/command-center.php" class="text-xs font-bold text-sharp-purple hover:text-white transition-colors flex items-center gap-2">
                <i data-lucide="arrow-left" class="w-4 h-4"></i> Back to Command Center
            </a>
        </div>

        <div class="bg-card-dark border border-white/5 rounded-xl overflow-hidden relative">
            <form method="POST" id="city-form" class="m-0 p-0">
                <input type="hidden" name="action" value="save_city_pillar">
                <input type="hidden" name="city_id" value="<?= esc_attr($edit_city_id) ?>">

                <div class="p-6 border-b border-white/5 bg-panel-dark/40 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                    <div class="flex items-center gap-4">
                        <select onchange="window.location.href='?edit_city='+this.value" class="bg-matte-black border border-white/10 text-white px-4 py-2 rounded-lg text-sm outline-none focus:border-sharp-purple min-w-[200px]">
                            <?php foreach($locations as $loc): ?>
                                <option value="<?= $loc->ID ?>" <?= $edit_city_id == $loc->ID ? 'selected' : '' ?>><?= esc_html($loc->post_title) ?></option>
                            <?php endforeach; ?>
                        </select>
                        <h3 class="font-syne text-lg font-bold text-white hidden md:block">Editing: <span class="text-blue-500" id="current-city-name"><?= esc_html($selected_city_name) ?></span></h3>
                    </div>
                    
                    <div class="flex items-center gap-3 w-full md:w-auto">
                        <button type="button" onclick="generateCityPillarWithAI()" class="flex-1 md:flex-none px-4 py-2 bg-blue-600/20 text-blue-400 border border-blue-500/30 rounded-lg text-sm font-bold hover:bg-blue-600 hover:text-white transition-all flex items-center justify-center gap-2">
                            <i data-lucide="sparkles" class="w-4 h-4"></i> AI Auto-Write
                        </button>
                        <button type="button" onclick="generateCityFAQs()" id="btn-gen-faqs" class="flex-1 md:flex-none px-4 py-2 bg-sharp-purple/20 text-sharp-purple border border-sharp-purple/30 rounded-lg text-sm font-bold hover:bg-sharp-purple hover:text-white transition-all flex items-center justify-center gap-2">
                            <i data-lucide="message-circle-question" class="w-4 h-4"></i> Generate AI FAQs
                        </button>
                        <button type="submit" class="flex-1 md:flex-none px-6 py-2 bg-success-green text-black rounded-lg text-sm font-bold shadow-[0_0_15px_rgba(74,222,128,0.3)] hover:bg-white transition-all flex items-center justify-center gap-2">
                            <i data-lucide="save" class="w-4 h-4"></i> Save Pillar
                        </button>
                    </div>
                </div>

                <div class="p-6 md:p-8">
                    <div class="p-4 bg-yellow-500/10 border border-yellow-500/20 rounded-lg text-sm text-lavender/80 flex gap-3 mb-6">
                        <i data-lucide="alert-triangle" class="w-5 h-5 text-yellow-500 flex-shrink-0 mt-0.5"></i>
                        <div>
                            <p class="font-bold mb-1">Backlinko / Brian Dean Content Engine Active</p>
                            <p>This generates beautifully formatted HTML intended for the bottom of the City Hub page. It uses short sentences and bucket brigades.
                        </div>
                    </div>

                    <div class="flex items-center justify-between mb-3">
                        <label class="block text-xs uppercase tracking-widest text-lavender/50">
                            Definitive Guide Content (Raw HTML)
                        </label>
                        <div class="flex items-center gap-3">
                            <span id="city-word-count" class="text-[10px] font-mono font-bold px-2 py-1 rounded border <?= str_word_count(strip_tags($selected_city_long_content)) >= 500 ? 'text-success-green bg-success-green/10 border-success-green/30' : 'text-yellow-400 bg-yellow-500/10 border-yellow-500/30' ?>">
                                <?= number_format(str_word_count(strip_tags($selected_city_long_content))) ?> words
                            </span>
                            <div class="flex items-center gap-2">
                                <button type="button" onclick="setCityView('source')" id="btn-source" class="px-3 py-1 text-[10px] font-bold rounded border bg-sharp-purple/20 text-sharp-purple border-sharp-purple/30">HTML</button>
                                <button type="button" onclick="setCityView('preview')" id="btn-preview" class="px-3 py-1 text-[10px] font-bold rounded border bg-white/5 text-lavender/50 border-white/10 hover:text-white">Preview</button>
                            </div>
                        </div>
                    </div>

                    <div id="view-source">
                        <textarea name="city_long_content" id="content-textarea" rows="25" oninput="updateWordCount(this)" class="w-full bg-[#0a0a0a] border border-white/10 rounded-lg p-4 text-white font-mono text-sm focus:border-sharp-purple outline-none leading-relaxed"><?= esc_textarea($selected_city_long_content) ?></textarea>
                    </div>

                    <div id="view-preview" class="hidden">
                        <div id="preview-frame" class="w-full min-h-[500px] bg-white text-[#111] rounded-lg p-8 prose prose-sm max-w-none overflow-auto leading-relaxed">
                            <?= wp_kses_post($selected_city_long_content) ?>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <!-- AI Overlay -->
    <div id="ai-loading-overlay" class="fixed inset-0 bg-black/90 z-[100] hidden items-center justify-center backdrop-blur-sm px-4">
        <div class="bg-card-dark border border-white/10 rounded-xl p-8 max-w-xl w-full flex flex-col items-center text-center shadow-2xl">
            <div class="w-16 h-16 rounded-full bg-blue-500/10 flex items-center justify-center mb-4 relative">
                <i data-lucide="bot" class="w-8 h-8 text-blue-400 relative z-10"></i>
                <div class="absolute inset-0 rounded-full border-2 border-blue-500 border-t-transparent animate-spin"></div>
            </div>
            <h3 class="font-syne text-xl font-bold text-white mb-2">Gemini AI is Writing...</h3>
            <p class="text-sm text-lavender/60 mb-4">Generating 700+ words of pillar content.</p>
            <div class="w-full bg-matte-black border border-white/5 rounded-lg p-4 text-left h-40 overflow-y-auto">
                <p id="ai-stream-output" class="text-xs font-mono text-blue-300 leading-relaxed opacity-70">Initializing stream...</p>
            </div>
        </div>
    </div>

    <script>
        lucide.createIcons();

        const apiKey = "AIzaSyC1DPDJzt5psEkIDgqK3XztuVLgXnDwwZM"; // Replace with your key
        const apiModel = "gemini-2.5-flash";

        const citySystemPrompt = `You are an elite SEO copywriter, trained in the exact writing style of Brian Dean (Backlinko).
Your task is to write a comprehensive, 700+ word "Definitive Local SEO Pillar" about digital dominance and web design in a specific City in Nigeria.

TONE & STYLE RULES (CRITICAL):
1. Use short sentences. Often just two to three sentence per paragraph.
2. Write at a 6th-grade reading level. Keep it accessible. No technical jargon.
3. Use "Bucket Brigades" to keep people reading (e.g., "Here is the truth:", "But there is a catch.", "Think about it.", "What does this mean for you?").
4. Speak directly to the business owner reading the page using "you" and "your".
5. Aggressive white space. Every HTML <p> MUST be 1 to 3 sentences MAX.
6. Our primary audience are business that do not have a website and what they are missing out. Our secondary audience is businesses that need an upgrade for their existing website or they need an infrastural upgrade. Maybe they need a mobile app, web portals, custom build, we have the skills.
7. Do not assume they need a website or digital upgrade for their local market only. They may be in a city but have a global business.
STRUCTURE (DO NOT INCLUDE A MAIN H1, Start with H2s):
- Start with a punchy hook about the business realities these days. How that most people go online to search for businesses. It helps build trust and connection immediately. It makes their business look credible, serious and trustworthy. 
- Use <h2> and <h3> tags to break up the content.
- Use <blockquote> tags for key takeaways (these will be styled beautifully on the frontend).
- Cover: The cost of being invisible in this city or Nigeria as a whole, why social media isn't enough", and how a real platform drives revenue, trust and growth.
- Frame GetOnline Studio not as an agency, but as a digital infrastructure partner. WHAT GETONLINE STUDIO ACTUALLY IS (read this carefully):
GetOnline Studio is NOT a web design company only. They are a DIGITAL INFRASTRUCTURE company. They help businesses, individuals, brands, and organizations GET ONLINE — many of whom currently have zero online presence beyond a WhatsApp number and an Instagram page. They educate, inspire, convince, and create urgency. They sell the IDEA of getting a proper digital home before they sell the service.

FORBIDDEN — NEVER USE IN ANY POST:
- "In Nigeria's competitive landscape" / "In today's digital age" / "In the digital era"
- "Elevate", "Unlock potential", "Take your business to the next level", "Seamless", "Bustling", "Vibrant"

OUTPUT FORMAT:
Return ONLY raw, beautifully formatted HTML. No markdown blocks. Use single quotes for HTML attributes if needed.`;

        async function generateCityPillarWithAI() {
            const cityName = document.getElementById('current-city-name').innerText;
            if (!confirm(`Generate a 700+ word definitive local guide for ${cityName}? This will overwrite the editor.`)) return;

            const overlay = document.getElementById('ai-loading-overlay');
            const streamOutput = document.getElementById('ai-stream-output');
            
            overlay.classList.remove('hidden');
            overlay.classList.add('flex');
            streamOutput.innerText = 'Connecting to Gemini AI...';

            try {
                const response = await fetch(
                    `https://generativelanguage.googleapis.com/v1beta/models/${apiModel}:streamGenerateContent?alt=sse&key=${apiKey}`,
                    {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json' },
                        body: JSON.stringify({
                            system_instruction: { parts: [{ text: citySystemPrompt }] },
                            contents: [{ role: 'user', parts: [{ text: `Write the 700+ word SEO pillar content for ${cityName}, Nigeria. Mention actual, real-world business districts in ${cityName}. Output ONLY HTML.` }] }],
                            generationConfig: { temperature: 0.7, maxOutputTokens: 8000 }
                        })
                    }
                );

                if (!response.ok) throw new Error(response.statusText);

                const reader = response.body.getReader();
                const decoder = new TextDecoder();
                let fullText = '';

                while (true) {
                    const { done, value } = await reader.read();
                    if (done) break;

                    const chunk = decoder.decode(value, { stream: true });
                    const lines = chunk.split('\n');

                    for (const line of lines) {
                        if (line.startsWith('data: ')) {
                            const jsonStr = line.slice(6).trim();
                            if (!jsonStr || jsonStr === '[DONE]') continue;
                            try {
                                const parsed = JSON.parse(jsonStr);
                                const token = parsed?.candidates?.[0]?.content?.parts?.[0]?.text || '';
                                if (token) {
                                    fullText += token;
                                    streamOutput.innerText = fullText.length > 250 ? '...' + fullText.slice(-250) : fullText;
                                    streamOutput.scrollTop = streamOutput.scrollHeight;
                                }
                            } catch (e) {}
                        }
                    }
                }

                // Clean markdown if AI accidentally includes it
                const finalHTML = fullText.replace(/```html/g, '').replace(/```/g, '').trim();

                const el = document.getElementById('content-textarea');
                el.value = finalHTML;
                updateWordCount(el);
                document.getElementById('preview-frame').innerHTML = finalHTML;
                
                streamOutput.innerText = 'Generation complete!';
                setTimeout(() => {
                    overlay.classList.add('hidden');
                    overlay.classList.remove('flex');
                }, 1000);

            } catch (error) {
                streamOutput.innerHTML = `<span class="text-red-400">Failed: ${error.message}</span>`;
                setTimeout(() => { overlay.classList.add('hidden'); overlay.classList.remove('flex'); }, 3000);
            }
        }

        function setCityView(mode) {
            const srcBtn = document.getElementById('btn-source');
            const prvBtn = document.getElementById('btn-preview');
            const srcView = document.getElementById('view-source');
            const prvView = document.getElementById('view-preview');
            const on = 'px-3 py-1 text-[10px] font-bold rounded border bg-sharp-purple/20 text-sharp-purple border-sharp-purple/30';
            const off = 'px-3 py-1 text-[10px] font-bold rounded border bg-white/5 text-lavender/50 border-white/10 hover:text-white';
            
            if (mode === 'source') {
                srcView.classList.remove('hidden'); prvView.classList.add('hidden');
                srcBtn.className = on; prvBtn.className = off;
            } else {
                document.getElementById('preview-frame').innerHTML = document.getElementById('content-textarea').value;
                srcView.classList.add('hidden'); prvView.classList.remove('hidden');
                srcBtn.className = off; prvBtn.className = on;
            }
        }

        function updateWordCount(textarea) {
            const text = textarea.value.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim();
            const words = text ? text.split(' ').filter(Boolean).length : 0;
            const badge = document.getElementById('city-word-count');
            badge.textContent = words.toLocaleString() + ' words';
            badge.className = 'text-[10px] font-mono font-bold px-2 py-1 rounded border transition-all ' + 
                (words >= 500 ? 'text-success-green bg-success-green/10 border-success-green/30' : 'text-yellow-400 bg-yellow-500/10 border-yellow-500/30');
        }

        function showFaqToast(msg, ok) {
            const t = document.getElementById('faq-toast');
            t.className = 'fixed top-6 right-6 z-[100] flex px-6 py-4 rounded-lg items-center gap-3 border text-sm font-bold ' +
                (ok ? 'bg-success-green/20 border-success-green/40 text-success-green' : 'bg-red-500/20 border-red-500/40 text-red-400');
            t.innerHTML = `<i data-lucide="${ok ? 'check-circle' : 'alert-circle'}" class="w-5 h-5"></i><span>${msg}</span>`;
            lucide.createIcons();
            setTimeout(() => t.classList.add('hidden'), 5000);
        }

        async function generateCityFAQs() {
            const cityId   = document.querySelector('[name="city_id"]').value;
            const cityName = document.getElementById('current-city-name').innerText;
            const btn      = document.getElementById('btn-gen-faqs');

            if (!confirm(`Generate AI FAQs for ${cityName}?\n\nThis will overwrite any previously saved FAQs for this city on the live hub page.`)) return;

            btn.disabled    = true;
            btn.innerHTML   = '<svg class="w-4 h-4 animate-spin" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 2v4M12 18v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83M2 12h4M18 12h4M4.93 19.07l2.83-2.83M16.24 7.76l2.83-2.83"/></svg> Generating...';

            try {
                const formData = new FormData();
                formData.append('action',  'generate_city_faqs');
                formData.append('city_id', cityId);

                const res  = await fetch(window.location.pathname, { method: 'POST', body: formData });
                const data = await res.json();

                showFaqToast(data.msg, data.ok);
            } catch (err) {
                showFaqToast('Request failed: ' + err.message, false);
            } finally {
                btn.disabled  = false;
                btn.innerHTML = '<i data-lucide="message-circle-question" class="w-4 h-4"></i> Generate AI FAQs';
                lucide.createIcons();
            }
        }
    </script>
</body>
</html>